#!/bin/bash -l

path_in=${1}
path_out=${2}
lrestmin=${4}
lrestmax=${5}
SNR_cut=${6}
noise=${7}
cat=${8}
lines=${9}
mode=${10}


mkdir -p ${path_out}/deltas
mkdir -p ${path_out}/log


picca_deltas.py \
--in-dir ${path_in} \
--drq ${cat} \
--out-dir ${path_out}/deltas \
--mode ${mode} \
--delta-format Pk1D \
--rebin 1 \
--lambda-min 3500. \
--lambda-max 7200.0 \
--lambda-rest-min ${lrestmin} \
--lambda-rest-max ${lrestmax} \
--nproc 16 \
--order 0 \
--use-constant-weight \
--coadd-by-picca \
--compute-diff-flux \
--use-desi-P1d-changes \
--mc-rebin-fac 4 \
--min-SNR ${SNR_cut} \
--mask-file ${lines} \
--log ${path_out}/log/log_deltas_lrestmin${lrestmin}_lrestmax${lrestmax}_SNR${SNR_cut} \
--iter ${path_out}/log/iter_deltas_lrestmin${lrestmin}_lrestmax${lrestmax}_SNR${SNR_cut}

mkdir -p ${path_out}/pk1d

picca_Pk1D.py \
--in-dir ${path_out}/deltas \
--in-format fits \
--out-dir ${path_out}/pk1d \
--lambda-obs-min 3750. \
--noise-estimate ${noise} \
--pixel-correction inverse \
--nproc 16 \
--use-desi-new-defaults \
--nb-pixel-masked-max 120 \
--nb-part 3 \
--SNR-min ${SNR_cut} \
--nb-noise-exp 2500
