#!/bin/bash -l

path_in="${1}"
path_out=${2}
path_log=${3}
suffix=${4}
snr_cut=${5}
noise_estimate=${6}


echo "input path for computation:"
echo $path_in
echo "output path for computation:"
echo $path_out
echo "log path for computation:"
echo $path_log
echo "specific suffix:"
echo $suffix
echo "SNR cut:"
echo $snr_cut
echo "noise estimate for p1d:"
echo $noise_estimate

if [[ ${suffix} == "None" ]]
then
suffix_flag=""
else
suffix_flag=${suffix}
fi





mkdir -p ${path_log}

mkdir -p ${path_out}/pk1d_${noise_estimate}_noise_estimate${suffix_flag}

picca_Pk1D.py \
--in-dir $path_in \
--in-format fits \
--out-dir ${path_out}/pk1d_${noise_estimate}_noise_estimate${suffix_flag} \
--lambda-obs-min 3750. \
--noise-estimate ${noise_estimate} \
--pixel-correction inverse \
--nproc 16 \
--use-desi-new-defaults \
--nb-pixel-masked-max 120 \
--nb-part 3 \
--SNR-min ${snr_cut} \
--nb-noise-exp 2500 > ${path_log}/log_p1d_out_${noise_estimate}_noise_estimate${suffix_flag} 2> ${path_log}/log_p1d_err_${noise_estimate}_noise_estimate${suffix_flag}
