#!/bin/bash -l

path_in="${1}"
suffix=${2}
snr_cut=${3}
noise_estimate=${4}
nb_proc=${5}


echo "input path for computation:"
echo $path_in
echo "specific suffix:"
echo $suffix
echo "SNR cut:"
echo $snr_cut
echo "noise estimate for p1d:"
echo $noise_estimate
echo "number of processors:"
echo $nb_proc


if [[ ${suffix} == "None" ]]
then
suffix_flag=""
else
suffix_flag=${suffix}
fi


mkdir -p ${path_in}/Log

mkdir -p ${path_in}/pk1d_SNRcut${snr_cut}${suffix_flag}


echo -e 'picca_Pk1D.py \
--in-dir '"${path_in}"'/Delta \
--in-format fits \
--out-dir '"${path_in}"'/pk1d_SNRcut'"${snr_cut}"''"${suffix_flag}"' \
--out-format fits \
--lambda-obs-min 3750. \
--noise-estimate '"${noise_estimate}"' \
--num-processors '"${nb_proc}"' \
--nb-pixel-masked-max 120 \
--nb-part 3 \
--SNR-min '"${snr_cut}"' \
--num-noise-exp 2500 > '"${path_in}"'/Log/p1d_output_SNRcut'"${snr_cut}"''"${suffix_flag}"' 2> '"${path_in}"'/Log/p1d_error_SNRcut'"${snr_cut}"''"${suffix_flag}"'' > ${path_in}/p1d_command_SNRcut${snr_cut}${suffix_flag}

bash ${path_in}/p1d_command_SNRcut${snr_cut}${suffix_flag}
